# Generated by Django 2.2.1 on 2019-05-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AULA',
        ),
    ]
