# Generated by Django 2.2.1 on 2019-05-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_aula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AULA',
        ),
    ]
