# Generated by Django 2.2.1 on 2019-05-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_aula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='data_criação',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='data_edição',
        ),
    ]
