# Generated by Django 2.2.1 on 2019-05-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_auto_20190508_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='data',
        ),
    ]
