# Generated by Django 2.2.1 on 2019-05-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_remove_aula_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
