# Generated by Django 2.2.1 on 2019-05-08 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0017_auto_20190508_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 8, 14, 13, 8, 662927)),
        ),
    ]
