# Generated by Django 2.2.1 on 2019-05-08 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0022_auto_20190508_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 8, 15, 0, 2, 222398)),
        ),
    ]
