# Generated by Django 2.2.1 on 2019-05-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0025_auto_20190508_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='data',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='email_autor',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='nome_autor',
        ),
    ]
