# Generated by Django 2.2.1 on 2019-05-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0026_auto_20190508_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AULA',
        ),
    ]
