# Generated by Django 2.2.1 on 2019-05-08 18:28

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulario', '0027_delete_aula'),
    ]

    operations = [
        migrations.CreateModel(
            name='AULA',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_autor', models.CharField(max_length=50)),
                ('email_autor', models.EmailField(blank=True, max_length=100, null=True)),
                ('titulo_aula', models.CharField(max_length=50)),
                ('descricao_aula', models.TextField(blank=True)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 8, 15, 28, 47, 639636))),
            ],
        ),
    ]
