# Generated by Django 2.2.1 on 2019-05-08 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0030_auto_20190508_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 8, 16, 45, 29, 998139)),
        ),
        migrations.AlterField(
            model_name='aula',
            name='descricao_aula',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aula',
            name='email_autor',
            field=models.EmailField(blank=True, default='Sem email:', max_length=100, null=True),
        ),
    ]
