# Generated by Django 2.2.1 on 2019-05-08 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0031_auto_20190508_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 8, 17, 27, 48, 95750)),
        ),
        migrations.AlterField(
            model_name='aula',
            name='email_autor',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
