# Generated by Django 2.2.1 on 2019-05-25 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0032_auto_20190508_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 25, 17, 34, 42, 663008)),
        ),
    ]
