# Generated by Django 2.2.1 on 2019-05-25 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0033_auto_20190525_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 25, 17, 35, 41, 467714)),
        ),
    ]
