# Generated by Django 2.2.1 on 2019-05-26 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0036_auto_20190525_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEXTO_AULA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_aula', models.CharField(max_length=100)),
                ('topico', models.CharField(max_length=50)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 25, 23, 43, 58, 434896)),
        ),
        migrations.AlterField(
            model_name='aula',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
