# Generated by Django 2.2.1 on 2019-05-26 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0038_auto_20190526_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 26, 16, 33, 20, 675440)),
        ),
    ]
