# Generated by Django 2.2.1 on 2019-05-26 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0039_auto_20190526_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 26, 16, 42, 16, 883880)),
        ),
        migrations.AlterField(
            model_name='texto_aula',
            name='codigo_aula',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
