# Generated by Django 2.2.1 on 2019-05-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0040_auto_20190526_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='data',
        ),
    ]
