# Generated by Django 2.2.1 on 2019-05-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0041_remove_aula_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['-number']},
        ),
        migrations.AlterModelOptions(
            name='texto_aula',
            options={'ordering': ['-id']},
        ),
    ]
