# Generated by Django 2.2.1 on 2019-05-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0043_auto_20190526_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='descricao_aula',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aula',
            name='titulo_aula',
            field=models.CharField(max_length=50),
        ),
    ]
