# Generated by Django 2.2.1 on 2019-05-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0044_auto_20190527_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texto_aula',
            options={'ordering': ['id']},
        ),
    ]
