# Generated by Django 2.2.1 on 2019-05-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EVENTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=50)),
                ('descricao_evento', models.TextField()),
                ('dia_evento', models.DateField()),
                ('hora_evento', models.CharField(max_length=16)),
            ],
        ),
    ]
