# Generated by Django 2.2.1 on 2019-05-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EVENTO',
        ),
    ]
