# Generated by Django 2.2.1 on 2019-05-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='link_evento',
            field=models.TextField(blank=True, default='null', null=True),
        ),
    ]
