# Generated by Django 2.2.1 on 2019-05-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_auto_20190508_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='link_evento',
        ),
    ]
