# Generated by Django 2.2.1 on 2019-05-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0008_evento_link_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='link_evento',
            field=models.CharField(blank=True, default='Sem link :(', max_length=200),
        ),
    ]
