# Generated by Django 2.2.1 on 2019-05-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0009_auto_20190508_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-dia_evento']},
        ),
    ]
